src/Laiso/ArmBundle/Entity/Marche.php
<?php

namespace Laiso\ArmBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Marche
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Laiso\ArmBundle\Repository\MarcheRepository")
 */
class Marche
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\Column(name="Numero", type="integer", nullable=true)
     */
    private $numero;

    /**
     * @var string
     *
     * @ORM\Column(name="Montant", type="float", nullable=true)
     */
    private $montant;

    /**
     * @var string
     *
     * @ORM\Column(name="AvancementPhysique", type="float", nullable=true)
     */
    private $avancementPhysique;

    /**
     * @var string
     *
     * @ORM\Column(name="AvancementFinancier", type="float", nullable=true)
     */
    private $avancementFinancier;

    /**
     * @var boolean
     *
     * Taxé ou pas! :)
     *
     * @ORM\Column(name="EntrepriseAssujettie", type="boolean")
     */
    private $entrepriseAssujettie;

    /***********************************************
     *                   ASSOCIATIONS
     *
     *    Ne surtout pas modifier les annotations
     *      sauf en cas de modification du modèle
     *
     *                  (c) Laiso
     ***********************************************/


    /**
     * Un marché est exercé par une et une seule entreprise,
     * mais une entreprise peut exercer plusieurs marchés
     *
     * Nullable à true pour la création de l'offre
     *
     * @ORM\ManyToOne(targetEntity="Laiso\ArmBundle\Entity\Entreprise", inversedBy="marches")
     * @ORM\JoinColumn(nullable=true, referencedColumnName="id")
     */
    private $entreprise;

    /**
     * Un marché est associeé à un seul lotissement (DAO)
     *
     * @ORM\OneToOne(targetEntity="Laiso\ArmBundle\Entity\Lotissement", inversedBy="marche")
     */
    private $lotissement;

    /**
     * @var
     *
     * @ORM\OneToMany(targetEntity="Laiso\ArmBundle\Entity\Avenant", mappedBy="marche")
     */
    private $avenants;
    /**
     * @var
     * @ORM\OneToMany(targetEntity="Laiso\ArmBundle\Entity\Avance", mappedBy="marche")
     */
    private $avances;


    /**
     * @return string
     */
    public function getObjet()
    {
        return $this->getLotissement()->getObjet();
    }

    /**
     * Count decompte
     * @return int
     */
    public function getDecomptes()
    {
        $c = 0;
        /** @var \Laiso\ArmBundle\Entity\Avenant $avenant */
        foreach ($this->avenants as $avenant) {
            $c = $c + count($avenant->getDecomptes());
        }
        return $c;
    }

    public function hasAvance()
    {
        /** @var \Laiso\ArmBundle\Entity\Avenant $avenant */
        foreach ($this->getAvenants() as $avenant) {
            /** @var \Laiso\ArmBundle\Entity\Decompte $decompte */
            foreach ($avenant->getDecomptes() as $decompte) {
                return $decompte->getNumero() == 0;
            }
        }
    }

    /**
     *
     * @return int|string
     */
    public function getMontantInitial(){
        /** @var \Laiso\ArmBundle\Entity\Avenant $avenant */
        $avenant = $this->avenants[0];
        $montant = 0;
        /** @var \Laiso\ArmBundle\Entity\LigneDQE $ligne */
        foreach ($avenant->getLignes() as $ligne) {
            $montant += $ligne->getQuantite() * $ligne->getPrix()->getPrixUnitaire();
        }
        return $montant;
    }

    /**
     * Marche constructor.
     */
    public function __construct()
    {
        $this->avenants = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set numero
     *
     * @param integer $numero
     *
     * @return Marche
     */
    public function setNumero($numero)
    {
        $this->numero = $numero;

        return $this;
    }

    /**
     * Get numero
     *
     * @return integer
     */
    public function getNumero()
    {
        return $this->numero;
    }

    /**
     * Set entreprise
     *
     * @param \Laiso\ArmBundle\Entity\Entreprise $entreprise
     *
     * @return Marche
     */
    public function setEntreprise(\Laiso\ArmBundle\Entity\Entreprise $entreprise = null)
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    /**
     * Get entreprise
     *
     * @return \Laiso\ArmBundle\Entity\Entreprise
     */
    public function getEntreprise()
    {
        return $this->entreprise;
    }


    function __toString()
    {
        return $this->numero . " - " . $this->lotissement->getCampagne()->getNumerotation();
    }

    /**
     * Set lotissement
     *
     * @param \Laiso\ArmBundle\Entity\Lotissement $lotissement
     *
     * @return Marche
     */
    public function setLotissement(\Laiso\ArmBundle\Entity\Lotissement $lotissement = null)
    {
        $this->lotissement = $lotissement;

        return $this;
    }

    /**
     * Get lotissement
     *
     * @return \Laiso\ArmBundle\Entity\Lotissement
     */
    public function getLotissement()
    {
        return $this->lotissement;
    }

    /**
     * Add avenant
     *
     * @param \Laiso\ArmBundle\Entity\Avenant $avenant
     *
     * @return Marche
     */
    public function addAvenant(\Laiso\ArmBundle\Entity\Avenant $avenant)
    {
        $this->avenants[] = $avenant;

        return $this;
    }

    /**
     * Remove avenant
     *
     * @param \Laiso\ArmBundle\Entity\Avenant $avenant
     */
    public function removeAvenant(\Laiso\ArmBundle\Entity\Avenant $avenant)
    {
        $this->avenants->removeElement($avenant);
    }

    /**
     * Get avenants
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getAvenants()
    {
        return $this->avenants;
    }

    /**
     * Add avance
     *
     * @param \Laiso\ArmBundle\Entity\Avance $avance
     *
     * @return Marche
     */
    public function addAvance(\Laiso\ArmBundle\Entity\Avance $avance)
    {
        $this->avances[] = $avance;

        return $this;
    }

    /**
     * Remove avance
     *
     * @param \Laiso\ArmBundle\Entity\Avance $avance
     */
    public function removeAvance(\Laiso\ArmBundle\Entity\Avance $avance)
    {
        $this->avances->removeElement($avance);
    }

    /**
     * Get avances
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getAvances()
    {
        return $this->avances;
    }

    /**
     * Set montant
     *
     * @param float $montant
     *
     * @return Marche
     */
    public function setMontant($montant)
    {
        $this->montant = $montant;

        return $this;
    }

    /**
     * Get montant
     *
     * @return float
     */
    public function getMontant()
    {
        return $this->montant;
    }

    /**
     * Set avancementPhysique
     *
     * @param float $avancementPhysique
     *
     * @return Marche
     */
    public function setAvancementPhysique($avancementPhysique)
    {
        $this->avancementPhysique = $avancementPhysique;

        return $this;
    }

    /**
     * Get avancementPhysique
     *
     * @return float
     */
    public function getAvancementPhysique()
    {
        return $this->avancementPhysique;
    }

    /**
     * Set avancementFinancier
     *
     * @param float $avancementFinancier
     *
     * @return Marche
     */
    public function setAvancementFinancier($avancementFinancier)
    {
        $this->avancementFinancier = $avancementFinancier;

        return $this;
    }

    /**
     * Get avancementFinancier
     *
     * @return float
     */
    public function getAvancementFinancier()
    {
        return $this->avancementFinancier;
    }

    /**
     * Set entrepriseAssujettie
     *
     * @param boolean $entrepriseAssujettie
     *
     * @return Marche
     */
    public function setEntrepriseAssujettie($entrepriseAssujettie)
    {
        $this->entrepriseAssujettie = $entrepriseAssujettie;

        return $this;
    }

    /**
     * Get entrepriseAssujettie
     *
     * @return boolean
     */
    public function getEntrepriseAssujettie()
    {
        return $this->entrepriseAssujettie;
    }
}

src/Laiso/ArmBundle/Form/DecompteType.php
<?php

namespace Laiso\ArmBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class DecompteType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('numero')
            ->add('dateDecompte', 'date', array(
                'widget' => 'single_text',
                'input' => 'datetime',
                'format' => 'dd/MM/yyyy'
            ))

        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Laiso\ArmBundle\Entity\Decompte'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'laiso_armbundle_decompte';
    }
}

src/Laiso/ArmBundle/Resources/views/Decompte/cpa.export.html.twig
{% extends '::export.html.twig' %}

{% block body %}
    {% include ('@LaisoArm/Decompte/cpa/content.html.twig') %}
{% endblock %}

src/Laiso/ArmBundle/Resources/views/Decompte/cpa.html.twig
{% extends '::base.html.twig' %}

{% block title %}Marché {{ entity.avenant.marche }} - CPA Décompte n° {{ entity.numero }}{% endblock %}

{% block breadcumbs %}
    <li><a href="{{ path('marche') }}">Marché</a></li>
    <li><a href="{{ path('marche_show', {'id' : entity.avenant.marche.id}) }}">Marché
            n° {{ entity.avenant.marche.numero }}</a></li>
    <li><a href="{{ path('decompte', {'marcheId': entity.avenant.marche.id}) }}">Décomptes</a></li>
    <li><a href="{{ path('decompte_show', {'marcheId': entity.avenant.marche.id, 'decompteId': entity.id}) }}">Décompte
            n° {{ entity.numero }} du {{ entity.dateDecompte|date('d M Y') }}</a></li>
    <li><a href="{{ path('decompte_cpa', {'marcheId': entity.avenant.marche.id, 'decompteId': entity.id}) }}">CPA</a>
    </li>
{% endblock %}

{% block body -%}
    {% include ('@LaisoArm/Decompte/cpa/content.html.twig') %}

    <a target="_blank" href="{{ path('decompte_export_cpa', {'marcheId': entity.avenant.marche.id, 'decompteId': entity.id}) }}" class="button primary">Exporter au format PDF</a>
{% endblock %}

src/Laiso/ArmBundle/Resources/views/Decompte/edit.html.twig
{% extends '::base.html.twig' %}

{% block title %}Marché {{ entity.avenant.marche }} - Décompte n° {{ entity.numero }}{% endblock %}

{% block body -%}
    {% include ('@LaisoArm/Decompte/includes/edit_decompte.html.twig') %}
    {{ form(delete_form) }}
{% endblock %}

src/Laiso/ArmBundle/Resources/views/Decompte/index.html.twig
{% extends '::base.html.twig' %}

{% block title %}
    Marché n° {{ marche }} - Décomptes
{% endblock %}

{% block breadcumbs %}
    <li><a href="{{ path('marche') }}">Marché</a></li>
    <li><a href="{{ path('marche_show', {'id' : marche.id}) }}">Marché n° {{ marche }}</a></li>
    <li><a href="{{ path('decompte', {'marcheId': marche.id}) }}">Décomptes</a></li>
{% endblock %}

{% set total = marche.montantInitial %}
{% set tva = marche.entrepriseAssujettie ? marche.lotissement.campagne.tVA : 0 %}
{% set montantDelivre = 0 %}
{% set nombreDecompte = 0 %}

{% block body -%}
    <div class="grid">
        <div class="row cells7">
            <div class="cell colspan2">
                <div class="panel">
                    <div class="heading">
                        <span class="title">Avancement</span>
                    </div>
                    <div class="content padding10">
                        <div class="laiso-bordered padding10 bg-white margin10 no-margin-left no-margin-right no-margin-top">
                            Montant HT: <br>
                            <span class="place-right tag primary">{{ total | separer }} Ar.</span>
                            <span class="clear-float"></span>
                            TVA: <br>
                            <span class="place-right tag primary">{{ (total * tva / 100) | separer }} Ar.</span>
                            <span class="clear-float"></span>
                            Montant TTC: <br>
                            <span class="place-right tag primary">{{ (total | tva(tva)) | separer }} Ar.</span>
                            <span class="clear-float"></span>
                            <hr class="thin">
                            <div class="align-center avancement laiso-bordered padding10">
                                {#<div data-role="preloader" data-type="cycle" data-style="color" style="margin:100px auto;"></div>
                                <p>Chargement de l'aperçu</p>#}
                                <h1 class="fg-green">{{ marche.avancementFinancier | separer }} %</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="cell colspan5">
                <div class="panel">
                    <div class="heading">
                        <span class="title">Décomptes provisoires</span>
                    </div>
                    <div class="content">
                        {% if entities | length > 0 %}
                            <div class="laiso-bordered padding10">

                                {% for entity in entities %}
                                    <div style="border: dashed darkgray 1px;"
                                         class="padding10 no-padding-top bg-white margin10 no-margin-left no-margin-right no-margin-top">
                                        <h4>
                                            <a href="{{ path('decompte_show', { 'decompteId': entity.id, 'marcheId': marcheId }) }}">Décompte provisoire n° {{ entity.numero }}{% if entity.dateDecompte %} du {{ (entity.dateDecompte|localizeddate('long', 'none')) |capitalize }}{% endif %}</a>

                                            {% if entity.numero == 0 %}
                                                <span class="place-right tag success">Avance de démarrage</span>
                                            {% endif %}
                                        </h4>
                                        <hr class="thin">
                                        <div class="grid">
                                            <div class="row cells12">
                                                <div class="cell align-center">
                                                    <span class='mif-2x mif-{{ entity.ferme ? "lock fg-black" : "unlock fg-green" }}'></span>
                                                </div>
                                                <div class="cell colspan11 padding10 no-padding-top no-padding-right no-padding-bottom" style="border-left: solid #adadad 3px">

                                                    {% set montantPartiel = entity.montantBrutHTVA %}

                                                    Montant brut <span class="place-right tag primary">{{ montantPartiel | separer }} Ar.</span>
                                                    {% if entity.numero > 0 %}
                                                        {% set montantDelivre = montantDelivre + montantPartiel %}
                                                    {% endif %}
                                                    <span class="clear-float">
                                                    Montant brut cumulé<span class="place-right tag primary"> {{ montantDelivre | separer }} Ar. </span>
                                                        <hr class="bg-gray">
                                                        {#<span class="place-right">
                                                            <ul class="inline-list no-margin">
                                                                <li><a href="#"><span class="mif-list"></span></a></li>
                                                                <li><a href="#"><span class="mif-file-text"></span></a></li>
                                                                <li><a href="#"><span class="mif-folder-open"></span></a></li>
                                                                <li><a href="#"><span class="mif-search"></span></a></li>
                                                            </ul>
                                                        </span>#}
                                                    {#<br>
                                                    Soit <span class="place-right tag primary">{{ (( montantPartiel) * 100 / total) | separer }}%</span><br>
                                                    Avancement financier <span class="place-right tag primary">{{ ((montantDelivre + montantPartiel) * 100 / total) | separer }}%</span>#}
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    {% set nombreDecompte = entity.numero %}
                                {% endfor %}

                                {% if nombreDecompte < delai %}
                                    <a class="button primary ajax-button"
                                       href="{{ path('decompte_new', {'marcheId': marcheId}) }}">
                                        Ajouter un nouveau décompte provisoire
                                    </a>

                                {% endif %}
                            </div>
                        {% else %}
                            <div class="laiso-bordered padding10 margin10 no-margin-left no-margin-right no-margin-bottom align-center">
                                <h3>Aucun décompte provisoire trouvé.</h3>
                                <hr class="thin" width="75%">
                                <a class="button warning ajax-button"
                                   href="{{ path('decompte_zero', {'marcheId': marcheId}) }}">
                                    Ajouter une avance de démarrage
                                </a>
                                <a class="button primary ajax-button"
                                   href="{{ path('decompte_new', {'marcheId': marcheId}) }}">
                                    Ajouter un nouveau décompte provisoire.
                                </a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/Laiso/ArmBundle/Resources/views/Decompte/new.html.twig
{% extends '::base.html.twig' %}

{% block title %}Marché {{ entity.avenant.marche }} - Nouveau Décompte{% endblock %}

{% block body -%}
    {%  include '@LaisoArm/Decompte/includes/new_decompte.html.twig' %}
{% endblock %}

src/Laiso/ArmBundle/Resources/views/Decompte/preview.html.twig
{% extends '::base.html.twig' %}

{% block title %}
    Marché n° {{ entity.avenant.marche }} - Décompte n° {{ entity.numero }}
{% endblock %}
{% block breadcumbs %}
    <li><a href="{{ path('marche') }}">Marché</a></li>
    <li><a href="{{ path('marche_show', {'id' : entity.avenant.marche.id}) }}">Marché n° {{ entity.avenant.marche }}</a></li>
    <li><a href="{{ path('decompte', {'marcheId': entity.avenant.marche.id}) }}">Décomptes</a></li>
    <li><a href="{{ path('decompte_show', {'marcheId': entity.avenant.marche.id, 'decompteId': entity.id}) }}">Décompte n° {{ entity.numero }} du {{ entity.dateDecompte|localizeddate('long', 'none') }}</a></li>
    <li><a href="{{ path('decompte_preview',{'marcheId': entity.avenant.marche.id, 'decompteId': entity.id} ) }}">DP Recto</a></li>
{% endblock %}

{% set tva = entity.avenant.marche.entrepriseAssujettie ? entity.avenant.marche.lotissement.campagne.tVA : 0 %}

{% block body %}
    <div class="laiso-bordered padding10 margin10 no-margin-left no-margin-right no-margin-bottom">
    <div class="align-center">
        <h4 class="text-bold">DIVISION TRAVAUX ENTRETIEN COURANT</h4>
        BLOC N° {{ entity.avenant.marche.lotissement.bloc.numero }} <br>
        ************<br>
        {{ entity.avenant.marche.lotissement.bloc.localisation | upper }} <br>
        ************<br>
    </div>

    <div class="grid">
        <div class="row cells5">
            <div class="cell offset3 colspan2">
                <table class="full-size">
                    <tr>
                        <td class="text-bold">GESTION</td>
                        <td>:</td>
                        <td class="align-right">{{ entity.avenant.marche.lotissement.campagne.gestion }}</td>
                    </tr>
                    <tr>
                        <td class="text-bold">BUDGET</td>
                        <td>:</td>
                        <td class="align-right">{{ entity.avenant.marche.lotissement.campagne.financementAbbr }}</td>
                    </tr>
                    <tr>
                        <td class="text-bold">MONTANT</td>
                        <td>:</td>
                        <td class="align-right text-bold">Ar. {{ (entity.avenant.marche.montant | tva(tva)) | separer }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <table>
        <tr>
            <td class="text-bold" style="width: 30%;">MARCHE N°</td>
            <td style="width: 3%;">:</td>
            <td>{{ entity.avenant.marche }}</td>
        </tr>

        <tr>
            <td class="text-bold">OBJET</td>
            <td>:</td>
            <td>{{ entity.avenant.marche.objet }}</td>
        </tr>
        <tr>
            <td class="text-bold">TITULAIRE</td>
            <td>:</td>
            <td>{{ entity.avenant.marche.entreprise }}</td>
        </tr>
        <tr>
            <td class="text-bold">MONTANT DE L'ACOMPTE</td>
            <td>:</td>
            <td class="text-bold align-center text-accent">Ar. {{ (resteAPayer | tva(tva)) | separer }}</td>
        </tr>
    </table>

    {% if entity.numero == 0 %}
        {% include '@LaisoArm/Decompte/print/zero.html.twig' %}
    {% else %}
        {% include '@LaisoArm/Decompte/print/default.html.twig' %}
    {% endif %}

    <a class="button primary" target="_blank" href="{{ path('decompte_print', {'decompteId': entity.id, 'marcheId': entity.avenant.marche.id}) }}">Exporter au format PDF</a>
{% endblock %}

src/Laiso/ArmBundle/Resources/views/Decompte/print.html.twig
{% extends '::export.html.twig' %}

{% set tva = entity.avenant.marche.entrepriseAssujettie ? entity.avenant.marche.lotissement.campagne.tVA : 0 %}

{% block body %}
    <div class="laiso-bordered padding10 margin10 no-margin-left no-margin-right no-margin-bottom">
    <div class="align-center">
        <h4 class="text-bold">DIVISION TRAVAUX ENTRETIEN COURANT</h4>
        BLOC N° {{ entity.avenant.marche.lotissement.bloc.numero }} <br>
        ************<br>
        {{ entity.avenant.marche.lotissement.bloc.localisation | upper }} <br>
        ************<br>
    </div>


    <table style="width: 80%; margin: auto;">
        <tr>
            <td width="60%"></td>
            <td class="text-bold">GESTION</td>
            <td>:</td>
            <td class="align-right">{{ entity.avenant.marche.lotissement.campagne.gestion }}</td>
        </tr>
        <tr>
            <td></td>
            <td class="text-bold">BUDGET</td>
            <td>:</td>
            <td class="align-right">{{ entity.avenant.marche.lotissement.campagne.financementAbbr }}</td>
        </tr>
        <tr>
            <td></td>
            <td class="text-bold">MONTANT</td>
            <td>:</td>
            <td class="align-right text-bold">Ar. {{ (entity.avenant.marche.montant | tva(tva)) | separer }}</td>
        </tr>
    </table>

    <table style="width: 80%; margin: auto;">
        <tr>
            <td class="text-bold" style="width: 30%;">MARCHE N°</td>
            <td style="width: 3%;">:</td>
            <td>{{ entity.avenant.marche }}</td>
        </tr>

        <tr>
            <td class="text-bold">OBJET</td>
            <td>:</td>
            <td>{{ entity.avenant.marche.objet }}</td>
        </tr>
        <tr>
            <td class="text-bold">TITULAIRE</td>
            <td>:</td>
            <td>{{ entity.avenant.marche.entreprise }}</td>
        </tr>
        <tr>
            <td class="text-bold">MONTANT DE L'ACOMPTE</td>
            <td>:</td>
            <td class="text-bold align-center text-accent">Ar. {{ (entity.montantAcompteHTVA | tva(tva)) | separer }}</td>
        </tr>
    </table>

    {% if entity.numero == 0 %}
        {% include '@LaisoArm/Decompte/print/zero.html.twig' %}
    {% else %}
        {% include '@LaisoArm/Decompte/print/default.html.twig' %}
    {% endif %}
{% endblock %}

src/Laiso/ArmBundle/Resources/views/Decompte/recapitulation.export.html.twig
{% extends '::export.html.twig' %}

{% block body %}
    {% set depensesFaites = 0 %}
    {% set retenues = 0 %}
    {% set restes = 0 %}
    {% set taxes = 0 %}

    {% set tva = entity.avenant.marche.entrepriseAssujettie ? entity.avenant.marche.lotissement.campagne.tVA : 0 %}

    {% if entity.numero == 0 %}
        {% include '@LaisoArm/Decompte/recapitulation/zero.html.twig' %}
    {% else %}
        {% include '@LaisoArm/Decompte/recapitulation/default.html.twig' %}
    {% endif %}
    <br><br><br>
    <div class="grid margin50 no-margin-left no-margin-right">
        <table>
            <tr>
                <td width="70%"></td>
                <td>
                    {{ entity.avenant.marche.lotissement.bloc.siege | upper }}, le {{ entity.dateDecompte | localizeddate('long', 'none') }} <br><br>
                    <span class="text-bold">Le Chargé d'Itinéraires, <br>Bloc n° {{ entity.avenant.marche.lotissement.bloc.numero }} </span>
                    <br><br><br><br><br>
                </td>
            </tr>
            <tr>
                <td></td>
                <td>

                </td>
            </tr>
        </table>
    </div>
{% endblock %}

src/Laiso/ArmBundle/Resources/views/Decompte/recapitulation.html.twig
{% extends '::base.html.twig' %}

{% block title %}Marché {{ entity.avenant.marche }} - Récapitulation du Décompte n° {{ entity.numero }}{% endblock %}
{% block breadcumbs %}
    <li><a href="{{ path('marche') }}">Marché</a></li>
    <li><a href="{{ path('marche_show', {'id' : entity.avenant.marche.id}) }}">Marché n° {{ entity.avenant.marche }}</a></li>
    <li><a href="{{ path('decompte', {'marcheId': entity.avenant.marche.id}) }}">Décomptes</a></li>
    <li><a href="{{ path('decompte_show', {'marcheId': entity.avenant.marche.id, 'decompteId': entity.id}) }}">Décompte n° {{ entity.numero }} du {{ entity.dateDecompte|localizeddate('long', 'none') }}</a></li>
    <li><a href="{{ path('decompte_recapitulation', {'marcheId': entity.avenant.marche.id, 'decompteId': entity.id}) }}">DP Verso</a></li>
{% endblock %}

{% block body %}

    {% set depensesFaites = 0 %}
    {% set retenues = 0 %}
    {% set restes = 0 %}
    {% set taxes = 0 %}

    {% set tva = entity.avenant.marche.entrepriseAssujettie ? entity.avenant.marche.lotissement.campagne.tVA : 0 %}

    {% include '@LaisoArm/Decompte/recapitulation/default.html.twig' %}

    <a class="button primary" target="_blank" href="{{ path('decompte_export_recapitulation', {'marcheId': entity.avenant.marche.id, 'decompteId': entity.id}) }}">Exporter au format PDF</a>
{% endblock %}